name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get version from package.json
      run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      
    - name: Build Docker Image
      run: docker build -t edumgt-nt:${{ env.PACKAGE_VERSION }} .
   
    - name: Setup key
      run: |
        set -eu
        mkdir "$HOME/.ssh"
        echo "${{ secrets.STAGE_ID_RSA }}" > "$HOME/.ssh/key"
        chmod 600 "$HOME/.ssh/key"
                  
    - name: Deploy Docker Container
      run: |
        docker save edumgt-nt | bzip2 | pv | ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.STAGE_SERVER_USER }}@${{ secrets.STAGE_SERVER_IP }} -p ${{ secrets.STAGE_SERVER_PORT }} 'bunzip2 | docker load'
