name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Getting version form package
      run: |
        apt update && apt install -y jq
        export VERSION=`jq -r ".version" < ./package.json`
    - 
      name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
    - 
      name: Build Docker Image
      run: docker build -t edumgt-nt:$VERSION .
    - 
      name: Log in to SSH Host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGE_SERVER_IP }}
        username: ${{ secrets.STAGE_SERVER_USER }}
        key: ${{ secrets.STAGE_ID_RSA }}
    - 
      name: Deploy Docker Container
      run: |
        docker save edumgt-nt | ssh ${{ secrets.STAGE_SERVER_USER }}@${{ secrets.STAGE_SERVER_IP }} -p ${{ secrets.STAGE_SERVER_PORT }} 'docker load'
