name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get version from package.json
      run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      
    - name: Build Docker Imageenv
      run: docker build -t edumgt-nt:${{ env.PACKAGE_VERSION }} .
    
    - id: ssh-stage
      # You may pin to the exact commit or the version.
      # uses: invi5H/ssh-action@ece33b57060e562f8d17b6c20b715de95204bbf2
      uses: invi5H/ssh-action@v1.0.0
      with:
        NAME: STAGE
        SSH_USER: ${{ secrets.STAGE_SERVER_USER }}
        SSH_HOST: ${{ secrets.STAGE_SERVER_IP }}
        SSH_PORT: ${{ secrets.STAGE_SERVER_PORT }}
        SSH_KEY: ${{ secrets.STAGE_ID_RSA }}
          
    - name: Deploy Docker Container
      run: |
        docker save edumgt-nt | bzip2 | pv | ssh ${{ steps.ssh-stage.outputs.SERVER }} 'bunzip2 | docker load'
